org: tonytangdeveloper
app: puplink
service: puplink
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${env:ENVIRONMENT}
    SUPBASE_DB_URL: ${env:SUPBASE_DB_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::puplink-bucket-${env:ENVIRONMENT}/*"

custom:
  bucketName: puplink-bucket-${env:ENVIRONMENT}

functions:
  upload:
    handler: src/handlers/upload.handler
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
    events:
      - httpApi:
          path: /upload
          method: post
  destroy:
    handler: src/handlers/destroy.handler
    events:
      - httpApi:
          path: /destroy
          method: post

resources:
  Resources:
    PuplinkBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedHeaders:
                - "*"
